AuthCrm/Controllers/CompanyController.cs
using AuthCrm.Data.DTOs;
using AuthCrm.Models.CompanyViewModels;
using AuthCrm.Service.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AuthCrm.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ICityService _cityService;

        public CompanyController(ICompanyService companyService, ICityService cityService)
        {
            _companyService = companyService;
            _cityService = cityService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _companyService.GetItems();
            return View(result);
        }

        public async Task<IActionResult> Create()
        {
            var model = new CreateViewModel
            {
                Company = new CompanyDto(),
                Cities = await _cityService.GetItems()
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            await _companyService.Insert(model.Company);
            return RedirectToAction("Index");
        }

        //public IActionResult Delete(int Id)
        //{
        //    var result = _companyService.GetById(Id);
        //    if (result != null)
        //    {
        //        _companyService.Delete(result);
        //    }
        //    return RedirectToAction("Index");
        //}

        public async Task<IActionResult> Update(int Id)
        {
            var result = await _companyService.GetById(Id);
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CompanyDto company)
        {
           await _companyService.Update(company);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(int Id)
        {
            var result = await _companyService.GetById(Id);
            return View(result);
        }
    }
}

AuthCrm/Controllers/CustomerController.cs
using AuthCrm.Service.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace AuthCrm.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;

        public CustomerController(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _customerService.GetItems();
            return View(result);
        }
        //public IActionResult Create()
        //{
        //List<SelectListItem> values = (from item in _companyService.GetCompanies()
        //                               select new SelectListItem()
        //                               {
        //                                   Text = item.CompanyName,
        //                                   Value = item.CompanyId.ToString()
        //                               }).ToList();
        //ViewBag.Companies = values;
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Create(Customer customer)
        //{
        //    _customerService.Add(customer);
        //    return RedirectToAction("Index");
        //}
        //public IActionResult Update(int Id)
        //{
        //List<SelectListItem> values = (from item in _companyService.GetCompanies()
        //                               select new SelectListItem()
        //                               {
        //                                   Text = item.CompanyName,
        //                                   Value = item.CompanyId.ToString()
        //                               }).ToList();
        //ViewBag.Companies = values;
        //var result = _customerService.GetByCustomerId(Id);
        //return View(result);
        //    return View();
        //}
        //[HttpPost]
        //public IActionResult Update(CustomerDetailDto model)
        //{
        //if (!ModelState.IsValid)
        //{
        //    return BadRequest();
        //}
        //var oldItem = _customerService.GetById(model.Id);

        //oldItem.CustomerName = model.CustomerName;
        //oldItem.CustomerNumber = model.CustomerNumber;
        //oldItem.CustomerEmail = model.CustomerEmail;
        //oldItem.CompanyId = model.CompanyId;
        //_customerService.Update(oldItem);
        //return RedirectToAction("Index");
        //    return Ok();
        //}
        //public IActionResult Delete(int Id)
        //{
        //    var result = _customerService.GetById(Id);
        //    if (result != null)
        //    {
        //        _customerService.Delete(result);
        //    }
        //    return RedirectToAction("Index");
        //}
        //public IActionResult Detail(int Id)
        //{
        //    var result = _customerService.GetByCustomerId(Id);
        //    return View(result);
        //}
    }
}

AuthCrm/Views/Shared/Components/SideBar/Default.cshtml
@using Microsoft.AspNetCore.Identity
@using AuthCrm.Data.Models
@inject UserManager<ApplicationUser> UserManager
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/Home/index">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Furkan Yıldırım@*@($"{(await UserManager.GetUserAsync(User)).FirstName}    {(await UserManager.GetUserAsync(User)).LastName}")*@</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/Home/Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Panel</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Arayüz
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-clipboard-check"></i>
            <span>Müşteriler</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Müşteriler:</h6>
                <a class="collapse-item" asp-controller="Customer" asp-action="Index">Genel Bakış</a>
                <a class="collapse-item" asp-controller="Customer" asp-action="Create">Müşteri Ekle</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Firmalar</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Kişisel Araçlar:</h6>
                <a class="collapse-item" asp-controller="Company" asp-action="Index">Genel Bakış</a>
                <a class="collapse-item" asp-controller="Company" asp-action="Create">Firma Ekle</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Eklentiler
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Sayfalar</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="/Identity/Account/Login">Login</a>
                <a class="collapse-item" href="/Identity/Account/Register">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Çizelgeler</span>
        </a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tablolar</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>
<!-- End of Sidebar -->